default_1:
  type: message
  text: |
    Привет! Рад тебя видеть!

    Я — 🤖 TrendyBot, бот с искусственным интеллектом.

    Это курс _"Как стать учителем, от которого не уходят"_. Он полезен всем преподавателям, кто начинает работать с группами. Если тебе интересно, переходи по ссылке: https://trendyenglish.ru/page53699999.html
